pipeline {
    agent any

    environment {
        mavenTool = 'Maven 3.9.4'
        gitRemoteUrl = 'https://github.com/shivanititan/Firebase-Remote.git'
    }

    stages {
        stage('Checkout code') {
            steps {
                checkout scm
            }
        }

        stage('Set up JDK') {
            steps {
                tool name: 'JDK 17', type: 'jdk'
            }
        }

         stage('Pull logs') {
            steps {
               script {
                  bat "git config --global user.name K-Sowjanya"
                  bat "git config --global user.email konudulasowjanya@titan.co.in"
                  bat "git pull origin main"  // Pull the latest changes from remote main branch
                  // bat "dir RemoteConfigPublisher/src/main/resources/ChangedFiles.txt"
                  bat "git log -n 1 --stat --name-status --format= -- RemoteConfigPublisher > RemoteConfigPublisher/src/main/resources/ChangedFiles.txt"
                  bat "git add RemoteConfigPublisher/src/main/resources/ChangedFiles.txt"
                  bat 'git commit -m "Write file names which have changes to ChangedFiles.txt"'
               }                 
            }
        }
        // stage('Push to GitRepo') {
        //     steps { 
        //         withCredentials([string(credentialsId: 'devops', variable: 'GITHUB_TOKEN')]) {
        //             // bat "git push origin HEAD:refs/heads/main"
        //             bat "git push https://${GITHUB_TOKEN}@github.com/shivanititan/Firebase-Remote.git HEAD:main"
        //         }
        //     }
        // }
         stage('Build with Maven') {
            steps {
                 tool name: mavenTool, type: 'hudson.tasks.Maven$MavenInstallation'
                 bat "\"${tool(name: mavenTool, type: 'hudson.tasks.Maven$MavenInstallation')}/bin/mvn\" -B clean compile package --file RemoteConfigPublisher/pom.xml"
            }
        }
        stage('Compile and Run Java Program') {
            steps {
                script {
                    def javaCmd = "${tool(name: 'JDK 17', type: 'jdk')}/bin/java"
                    bat "\"${javaCmd}\" -cp \"C:/ProgramData/Jenkins/.jenkins/workspace/Firebase_Remote_Config/RemoteConfigPublisher/target/RemoteConfigPublisher-1.0-SNAPSHOT.jar\" com.titan.RemoteConfigPublisher"
                }
            }
        }
    }
    //     post {
    //     // Clean after build
    //     always {
    //           cleanWs(cleanWhenNotBuilt: false,
    //                 cleanWhenSuccess: true)
    //        }
    //     }
 }


